### ISSUE TITLE
Installing libraries before pip install

### ISSUE THREAD

**Issue by kvarga** [heroku/docker-python#1]
I need to install "libxmlsec1-dev" from apt-get BEFORE this runs. I tried adding it to ONBUILD RUN /app/.heroku/python/bin/pip install -r requirements.txt

However, I can never seem to get environment right even if ```docker-compose build``` runs. I get errors like ```Cannot start container.....: [8] System error: exec: "gunicorn": executable file not found in $PATH```

Is github the  latest from DockerHub? If I copy paste https://raw.githubusercontent.com/heroku/docker-python/master/Dockerfile into Dockerfile, I'd expect the same result as ```FROM heroku/python``` but get this error: ```Cannot start container .......: [8] System error: exec: "/usr/bin/init": permission denied```

**Comment by friism** [comment]
@kvarga you're going to have to create your own image, eg kvarga/python and then `FROM kvarga/python` to get that to work.
